name: PR Build

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft

concurrency:
  group: ${{ github.workflow }}-PR-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.pull_request.draft == false }}
    name: "Build"
    uses: ./.github/workflows/node.js.yml
    with:
      namespace: "pr"

